[package]
name = "gphoto2"
description = "Rust wrapper for libbgphoto2"
version = "0.1.0"
edition = "2021"
keywords = ["gphoto2", "gphoto", "libgphoto"]
authors = ["Maxicarlos08 <maxicarlos08@gmail.com>"]
license-file = "LICENSE"
repository = "https://git.maxicarlos.de/maxicarlos08/gphoto2-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["libgphoto2-sys"]

[dependencies]
libgphoto2_sys = { path = "libgphoto2-sys" }
